#ifndef EGUANA_TUNNELING_H
#define EGUANA_TUNNELING_H

#define MAX_INTERLAKE_SYSTEM_SIZE 10
#define MASTER_SYSTEM_HOST_ID 6

#define SSH_TCP_PORT 22
#define GW_TCP_PORT 8080
#define TIVA_TCP_PORT 502

#define EMC_NETWORK_BRIDGE_IP_ADDRESS "10.3.2.1"
#define TIVA_TCP_IP_ADDRESS "169.254.0.5"
#define TIVA_RS485_IP_ADDRESS EMC_NETWORK_BRIDGE_IP_ADDRESS

#define TIVA_SERVICE_ID_PREFIX "TIVA_"
#define TIVA_TCP_IP_ADDRESS_PREFIX "169.254.0."

#endif // EGUANA_TUNNELING_H